---

antora:
  name: modules
  dir: www
  modules:
    - name: module-01
      label: "Configuring Ansible Lightspeed in Visual Studio Code"
      solveButton: false
    - name: module-02
      label: "Deploy and Configure Cockput using Ansible Lightspeed"
      solveButton: false
    - name: module-03
      label: "PostgreSQL Server and PG Admin container"
      solveButton: false
    - name: module-04
      label: "Provision an EC2 instance"
      solveButton: false
    - name: module-05
      label: "Provision an Azure VM"
      solveButton: false
    - name: module-06
      label: "Playground and Model customization"
      solveButton: false

tabs:
  - name: VS Code
    url: https://vscode-${guid}.${domain}/?folder=/home/rhel/acme_corp
    external: true
  - name: Ansible Automation Platform
    url: https://control-${guid}.${domain}/
  - name: Cockpit
    url: https://cockpit-${guid}.${domain}/
  - name: PgAdmin
    url: https://pgadmin-${guid}.${domain}/
  - name: AWS/Azure
    url: /cloud
  - name: gitea
    url: https://gitea-${guid}.${domain}/
